# build environment
FROM node:12.3.1-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN yarn install --silent --frozen-lockfile
RUN yarn global add @quasar/cli@1.2.2
COPY . /app
RUN quasar build

# production environment
FROM nginx:1.19.0-alpine
COPY --from=build /app/dist/spa /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
