version: '3.7'

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mdillon/postgis:11
    ports:
      - 5432:${SQL_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ncenviroscan
      - POSTGRES_PASSWORD=ncenviroscan
      - POSTGRES_DB=ncenviroscan_dev

volumes:
  postgres_data:
