# Generated by Django 3.1.7 on 2021-05-06 21:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acs_2019_5y_estimates_geom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid10', models.TextField(verbose_name=2)),
                ('percent_below_poverty_level', models.FloatField(null=True)),
                ('speak_a_language_other_than_english', models.FloatField(null=True)),
                ('two_or_more_races', models.FloatField(null=True)),
                ('asian_alone', models.FloatField(null=True)),
                ('american_indian_and_alaska_native_alone', models.FloatField(null=True)),
                ('native_hawaiian_and_other_pacific_islander_alone', models.FloatField(null=True)),
                ('white_alone', models.FloatField(null=True)),
                ('black_or_african_american_alone', models.FloatField(null=True)),
                ('not_hispanic_or_latino', models.FloatField(null=True)),
                ('hispanic_or_latino_of_any_race', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'drf_acs_2019_5y_estimates_geom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='acs_2019_5y_estimates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid10', models.TextField(verbose_name=2)),
                ('percent_below_poverty_level', models.FloatField(null=True)),
                ('speak_a_language_other_than_english', models.FloatField(null=True)),
                ('two_or_more_races', models.FloatField(null=True)),
                ('asian_alone', models.FloatField(null=True)),
                ('american_indian_and_alaska_native_alone', models.FloatField(null=True)),
                ('native_hawaiian_and_other_pacific_islander_alone', models.FloatField(null=True)),
                ('white_alone', models.FloatField(null=True)),
                ('black_or_african_american_alone', models.FloatField(null=True)),
                ('not_hispanic_or_latino', models.FloatField(null=True)),
                ('hispanic_or_latino_of_any_race', models.FloatField(null=True)),
            ],
        ),
    ]
